### PR TITLE
Added new PR stuff to FAQ

### PR DESCRIPTION
**Pull request by bsonefeld**
### Added
* RWD podcast
* UX Pin talk
* Josh's article about Data Tables

### CODE REVIEW

**Comment by tay-aitken** [comment]
👍 ✅ 
## Requested Changes
- [ ] `src/app/components/custom/ArticleTiles/ArticleTiles.js` > line 54: capitalize Blue.
- `src/app/components/custom/FeaturedTiles/FeaturedTiles.js` > 
  - [ ] line 33: Capitalize all words since its the title of the award
  - [ ] line 46: Capitalize all words since its the title of the award

**Comment by bsonefeld** [comment]
@tay-aitken addressed comments and added in the What's New content, could you take a look? 

screen shot 2018-02-21 at 3 37 38 pm

**Comment by bsonefeld** [comment]
Crap, I just realized the date is wrong.. changed to **February 23rd, 2018.**

**Comment by tay-aitken** [comment]
@bsonefeld The only thing that looks off is the picture for the plugins since the palette showing is not Carbon colors.

**Pull request merged**
