### PR TITLE
Added in new utility section

### PR DESCRIPTION
**Pull request by tay-aitken**
Few questions I need to get cleared up:

1. Should we call this section something broader than cursors? If not should I remove browser tooltip?
2. Should we add in more cursor types? These are the only ones we currently have built into the componentes but we can add in more. 
3. I am worried about having image examples in the cursor chart since some of them  are white and are pages are white. Could we instead have each cursors appear on row hover? @marijohannessen is this something we can do?

Note: I am still adding in more content, just wanted to do an initial review of the work from you two.

### CODE REVIEW

**Comment by aagonzales** [comment]
1. I could see this category expanding beyond just cursors. Something like "OS and Browser elements" ... kind of a long title though. Because I think cursors are OS level and tooltips are browser level. Or maybe just "Operational elements" or "system defaults"?

I'm also ok with leaving it as "Cursors" for now.

2. If we think there are validate use cases for the other cursors than yes. But if its too confusing then I would say we should wait until they are actually used to define them. I like that you link out to the others. 

3. I like the idea of them showing up on hover but I like having them in the chart as well. Maybe we can just add a background to the white ones?

**Comment by aagonzales** [comment]
Leave tooltips in. I think there will be other "system" elements we can expand on in a section like this.

**Comment by marijohannessen** [comment]
Yes, I can fix that! Let's merge this PR in first and then I can add that before we deploy

**Comment by tay-aitken** [comment]
@marijohannessen one thing I noticed is that images are quite large dues to this class & CSS
`.page_md img {
     width: 100%;
}`

If the width is turned off the images appear at the proper size. When you look into the hover effect could you fix the image sizing?

**Comment by tay-aitken** [comment]
🎉

**Pull request merged**
