### PR TITLE
feat(404): add new 404 page

### PR DESCRIPTION
**Pull request by tw15egan**
Revamp the 404 page

Closes https://github.ibm.com/Bluemix/carbon-issues/issues/376

screen shot 2018-01-04 at 12 22 10 pm

### CODE REVIEW

**Comment by marijohannessen** [comment]
It looks like the background is supposed to be #F9F9FD. Can @aagonzales confirm?

**Comment by marijohannessen** [comment]
The text beneath the heading should be #5A6873.

**Comment by marijohannessen** [comment]
I think we need to modify it a bit on smaller screens, maybe just adjust the text size and the image size a bit and move it up a little bit

screen shot 2018-01-05 at 10 15 03 am

**Comment by marijohannessen** [comment]
👍 ✅ ❗️

**Comment by aagonzales** [comment]
Yes the background color should be: #F9F9FD
Text color: title/larger text= text-01 and the sub/smaller text is text-02 (#5A6872)

And yes I agree @marijohannessen we need a better mobile version (my bad for not thinking about that).  Let's say
- [ ] Below 768 size screens the image should be set to 80% of screen width
- [ ] And decrease the title text to 20px

image

**Comment by marijohannessen** [comment]
Perfect! 👍 ✅

**Pull request merged**
