### PR TITLE
S360 Motion Content Update

### PR DESCRIPTION
**Pull request by dinaerdianinque**
## Changed

**Changed motion guide content in file:** 

`src/content/style/motion/motion.md`

**Updated motion guide examples in file:** 

`src/internal/MotionExample/motion-example.scss`
`src/internal/MotionExample/MotionExample.js`

## Added 

**Added motion spec to components that describes the component updates in Wonil's PRs**

`src/content/components/button/style.md`
`src/content/components/dropdown/style.md`
`src/content/components/overflow-menu/style.md`
`src/content/components/toggle/style.md`

### CODE REVIEW

**Comment by dinaerdianinque** [comment]
# Motion Guide page build
motion-guide

**Comment by bsonefeld** [comment]
Looks awesome! Thanks for creating the staging link, that was super helpful to see it in prod. 

✅  👍

**Comment by tw15egan** [comment]
@dinaerdianinque could you delete the `package-lock.json` file and instead use `yarn` to install dependencies? Should shrink down the size of the PR as well 😄

**Comment by tw15egan** [comment]
BTW, changes look good to me! 👍 ✅

**Comment by dinaerdianinque** [comment]
Awesooome!! Thanks for reviewing!

**Comment by marijohannessen** [comment]
Waiting to merge this in until the motion updates are merged into the components.

**Comment by marijohannessen** [comment]
We're going to wait until Motion is more fleshed out from Duo's side. We can re-open this PR when we're ready to add it in.

**Pull request closed without merging**
