### PR TITLE
Dropdown docs: updates

### PR DESCRIPTION
**Pull request by bsonefeld**
## Changed
* `usage.md` , `style.md`, and images added for new Dropdown component (Combobox, multiselect, dropdown V2)
* Fixed 2 service provider images that were outdated

## Additional help
* Needs actual new Dropdown component added to `code.md`

### CODE REVIEW

**Comment by tay-aitken** [comment]
Few updates:
- [ ] `src/content/components/dropdown/images/dropdown-style-1.png` Option 3 on “Open - new selection“ still appears to be in Helvetica, can you please swap it to Plex. (I can make the change and send it to you if need be but want it to be included in your PR)
- [ ]  `src/content/components/dropdown/images/dropdown-usage-2.png` `src/content/components/dropdown/images/dropdown-usage-3.png` `src/content/components/dropdown/images/dropdown-usage-4.png` the large labels above components need to be changed to our small labels under the components and all components need to be centered on the artboard
- [ ] Also are all these image width and heights meeting our requirements for the style tab? they seem to be random sizes.
- `src/content/components/dropdown/style.md` 
  - [ ] line 10: remove label and change it to say **Placeholder text: filter**, its not really a label at the point and that would keep it consistent with how its named in other charts on the page
  - [ ] line 22 & 26: we do not use bold but semi-bold, what was there originally was correct. if the file is in bold it needs to be switched to semi-bold
  - [ ] Line 53 & 76: change “Spacing: checkbox & checkbox label“ to “Spacing: checkbox & label“
- `src/content/components/dropdown/usage.md`
  - [ ] line 6: there is an extra space between cannot and be
  - [ ] line 6: I would put filter dropdown in the row above Multi-select Dropdown 
  - [ ] line 10: menus should not be capitalized
  - [ ] line 14: change “list of options of a Dropdown“ to “list of Dropdown options“

**Comment by tay-aitken** [comment]
@bsonefeld ^^

**Comment by tay-aitken** [comment]
👍 ✅ 
- [ ] `src/content/components/dropdown/style.md` line 22 & 26: 700 > 600

- `src/content/components/dropdown/usage.md` 
  - [ ] Line 5: May only be used with Dropdown or Multi-select Dropdown and cannot be used with Inline Dropdown.  > May only be used with Dropdown or Multi-select Dropdown. Cannot be used with Inline Dropdown.  
  - [ ] Line 10: This can be seen in the [Tabs](/components/tabs) component, which at a smaller screen size collapses into a Dropdown. > This can be seen in [Tabs](/components/tabs), when used in a smaller screen size, collapses into a Dropdown.
  - [ ] line 23: (single or multi-select) > capitalize Multi-select?
  - [ ] line 39: user-inputted type > user-inputted text
  - [ ] line 48: element to close drawer > element to close the drawer

**Comment by marijohannessen** [comment]
I'm going to merge this on Monday when I start working on displaying the dropdowns on the website!

**Pull request merged**
